# Predictability analysis parameters

COR_THRE = "well_predicted"

MAIN_TISSUES = c(# "Adipose-Subcutaneous",
                 "Adipose-Visceral(Omentum)",
                 "Artery-Tibial",
                 "WholeBlood",
                 "Brain","Breast-MammaryTissue",
                 # "Colon-Transverse",
                 "Esophagus-Mucosa",
                 # "Esophagus-Muscularis",
                 # "Lung","Muscle-Skeletal","Nerve-Tibial",
                 # "Skin-NotSunExposed(Suprapubic)",
                 "Testis","Thyroid")

MAIN_TISSUES_GSEA <- c("Adipose-Visceral(Omentum)" = "AdiposeVisceral",
                       "Artery-Tibial" = "ArteryTibial",
                       "WholeBlood" = "WholeBlood", "Brain" = "Brain",
                       "Breast-MammaryTissue" = "BreastMammaryTissue",
                       "Esophagus-Mucosa" = "EsophagusMucosa",
                       "Testis" = "Testis", "Thyroid" = "Thyroid")

ALL_TISSUES_GSEA <- c("Adipose-Subcutaneous" = "AdiposeSubcutaneous",
                      "Adipose-Visceral(Omentum)" = "AdiposeVisceral",
                      # "Adrenal Gland" = "AdrenalGland",
                      # "Artery-Coronary" = "ArteryCoronary",
                      "Artery-Tibial" = "ArteryTibial",
                      "WholeBlood" = "WholeBlood", "Brain" = "Brain",
                      "Breast-MammaryTissue" = "Breast",
                      "Colon-Transverse" = "ColonTransverse",
                      "Esophagus-Mucosa" = "EsophagusMucosa",
                      "Esophagus-Muscularis" = "EsophagusMuscularis",
                      # "Heart-Attrial Appendage" = "HeartAttrialAppendage",
                      # "Heart-Left Ventricle" = "HeartLeftVentricle",
                      # "Liver" = "Liver",
                      "Lung" = "Lung",
                      # "Minor Salivary Gland" = "MinorSalivaryGland",
                      "Muscle-Skeletal" = "MuscleSkeletal",
                      "Nerve-Tibial" = "NerveTibial",
                      # "Ovary" = "Ovary", "Pancreas" = "Pancreas",
                      # "Pituitary" = "Pituitary", "Prostate" = "Prostate",
                      "Skin-NotSunExposed(Suprapubic)" = "SkinNotSunExposed",
                      "Skin-SunExposed(Lower Leg)" = "SkinSunExposed",
                      # "Small Intestine" = "SmallIntestine",
                      # "Spleen" = "Spleen",
                      "Testis" = "Testis",
                      "Thyroid" = "Thyroid",
                      # "Uterus" = "Uterus",
                      # "Vagina" = "Vagina",
                      NULL)
ALL_TISSUES <- c("Adipose-Subcutaneous", "Adipose-Visceral(Omentum)",
                 "Artery-Tibial", "WholeBlood", "Brain", "Breast-MammaryTissue",
                 "Colon-Transverse", "Esophagus-Mucosa", "Esophagus-Muscularis",
                 "Lung", "Muscle-Skeletal", "Nerve-Tibial",
                 "Skin-NotSunExposed(Suprapubic)", "Skin-SunExposed(Lowerleg)",
                 "Testis", "Thyroid")

N_TOP = 100

tissue_labels_dash <- c("Adipose-Subcutaneous" = "Adipose - Subcutaneous",
                        "Adipose-Visceral(Omentum)" = "Adipose - Visceral",
                        "Artery-Tibial" = "Artery - Tibial",
                        "Brain" = "Brain",
                        "Breast-MammaryTissue" = "Breast - Mammary Tissue",
                        "Colon-Transverse" = "Colon - Transverse",
                        "Esophagus-Mucosa" = "Esophagus - Mucosa",
                        "Esophagus-Muscularis" = "Esophagus - Muscularis",
                        "Lung" = "Lung",
                        "Muscle-Skeletal" = "Muscle - Skeletal",
                        "Nerve-Tibial" = "Nerve - Tibial",
                        "Skin-NotSunExposed(Suprapubic)" = "Skin - Not sun exposed",
                        "Skin-SunExposed(Lowerleg)" = "Skin - Sun exposed",
                        "Testis" = "Testis", "Thyroid" = "Thyroid", "WholeBlood" = "Blood")

tissue_labels_dash_all <- c("Adipose-Subcutaneous" = "Adipose - Subcutaneous",
                            "Adipose-Visceral(Omentum)" = "Adipose - Visceral",
                            "AdrenalGland" = "Adrenal Gland",
                            "Artery-Coronary" = "Artery - Coronary",
                            "Artery-Tibial" = "Artery - Tibial",
                            "Brain" = "Brain",
                            "Breast-MammaryTissue" = "Breast - Mammary Tissue",
                            "Colon-Transverse" = "Colon - Transverse",
                            "Esophagus-Mucosa" = "Esophagus - Mucosa",
                            "Esophagus-Muscularis" = "Esophagus - Muscularis",
                            "Heart-AtrialAppendage" = "Heart - Attrial Appendage",
                            "Heart-LeftVentricle" = "Heart - Left Ventricle",
                            "Liver" = "Liver", "Lung" = "Lung",
                            "MinorSalivaryGland" = "Minor Salivary Gland",
                            "Muscle-Skeletal" = "Muscle - Skeletal",
                            "Nerve-Tibial" = "Nerve - Tibial", "Ovary" = "Ovary",
                            "Pancreas" = "Pancreas", "Pituitary" = "Pituitary",
                            "Prostate" = "Prostate",
                            "Skin-NotSunExposed(Suprapubic)" = "Skin - Not sun exposed",
                            "Skin-SunExposed(Lowerleg)" = "Skin - Sun exposed",
                            "SmallIntestine-TerminalIleum" = "Small Intestine",
                            "Spleen" = "Spleen",
                            "Testis" = "Testis", "Thyroid" = "Thyroid",
                            "Uterus" = "Uterus", "Vagina" = "Vagina",
                            "WholeBlood" = "Blood")
